/*
 * Name: Sheyla Trudo
 * Course: CSCE 320
 * Semester: Spring 2015
 * Language: Java
 * IDE: Netbeans 8.0.2
 * Date: 3/9/2015
 * 
 * Sources Consulted:
 *      Dr. George Hauser
 *
 * Revision History:
Commits on Mar 9, 2015
    Final Fixes 
    The lab for now has been completed. I changed minor items regarding the
    view. Eventually I would like to handle the error that the Clients get
    when I close out of the server with the Clients still running.

    Begin Testing 
    So far initial tests have been relatively successful.  The clients are
    able to connect to the server and send messages to each other. Minor
    editing within the displayed text. Some errors: A repetitive text is
    displayed on the client views if the server is closed out of during
    connection. Also the server still needs to display client messages.

    Editing Controller and Server Start Button 
    Setting up the Controller and Connection classes and each of their
    separate functions. Also added a start button to allow the server to
    begin.

    View Set Up and MVC Set Up 
    Designed the Server View and set up the connections between the MVC
    components.

Commits on Mar 7, 2015
    Initializing Classes Part 2
 */
package lab2.server;

import java.util.Date;

/**
 *
 * @author Sheyla
 */
public class ServerView extends javax.swing.JPanel {

    ServerController controller;
    
    /**
     * Creates new form ServerView
     */
    public ServerView() {
        initComponents();
    }

    /**
     * Sets the controller for the view. 
     * @param controller    The controller for the view.
     */
    public void setController( ServerController controller ){ this.controller = controller; }
    
    /**
     * Appends a line of text to the JTextArea, txtLog.
     * @param message   The line of text to append to txtLog.
     */
    public void logMessage( String message )
    { 
        if( "".equals(txtLog.getText()) )
        {
            txtLog.setText( message );
        }
        else{ txtLog.setText( txtLog.getText() + "\n" +  message ); }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        txtMessage = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        txtMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMessage.setText("Enter message here and press ENTER to send.");
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        if( !"".equals(txtMessage.getText()) ){ controller.sendMessage( new Date().toString() + ": SERVER: " + txtMessage.getText().trim() ); }
        txtMessage.setText("");
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        controller.startServer();
        logMessage("Server Begin. . .");
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtLog.setText("");
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
